// <auto-generated />
using System;
using FindMyStuff.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FindMyStuff.Data.Migrations
{
    [DbContext(typeof(FindMyStuffDBContext))]
    [Migration("20200102164305_AddingPrimarykeysRequired")]
    partial class AddingPrimarykeysRequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FindMyStuff.Data.Models.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("DocumentTypeId");

                    b.Property<string>("Picture")
                        .HasColumnName("picture")
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("FindMyStuff.Data.Models.DocumentType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("FindMyStuff.Data.Models.DocumentXperson", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("DateFound")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateLost")
                        .HasColumnType("date");

                    b.Property<long>("DocumentId");

                    b.Property<long>("PersonId");

                    b.Property<bool?>("WasFound");

                    b.Property<bool?>("Wasloosed");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("PersonId");

                    b.ToTable("DocumentXPerson");
                });

            modelBuilder.Entity("FindMyStuff.Data.Models.Person", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("FindMyStuff.Data.Models.Document", b =>
                {
                    b.HasOne("FindMyStuff.Data.Models.DocumentType", "DocumentType")
                        .WithMany("Document")
                        .HasForeignKey("DocumentTypeId")
                        .HasConstraintName("FK_Document_DocumentType");
                });

            modelBuilder.Entity("FindMyStuff.Data.Models.DocumentXperson", b =>
                {
                    b.HasOne("FindMyStuff.Data.Models.Document", "Document")
                        .WithMany("DocumentXperson")
                        .HasForeignKey("DocumentId")
                        .HasConstraintName("FK_DocumentXPerson_Document");

                    b.HasOne("FindMyStuff.Data.Models.Person", "Person")
                        .WithMany("DocumentXperson")
                        .HasForeignKey("PersonId")
                        .HasConstraintName("FK_DocumentXPerson_Person");
                });
#pragma warning restore 612, 618
        }
    }
}
