USE [master]
GO
/****** Object:  Database [FindMyStuffDB]    Script Date: 12/31/2019 9:08:03 AM ******/
CREATE DATABASE [FindMyStuffDB]

GO
ALTER DATABASE [FindMyStuffDB] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FindMyStuffDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FindMyStuffDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FindMyStuffDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FindMyStuffDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FindMyStuffDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FindMyStuffDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FindMyStuffDB] SET  MULTI_USER 
GO
ALTER DATABASE [FindMyStuffDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FindMyStuffDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FindMyStuffDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FindMyStuffDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FindMyStuffDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FindMyStuffDB] SET QUERY_STORE = OFF
GO
USE [FindMyStuffDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [FindMyStuffDB]
GO
/****** Object:  Table [dbo].[Document]    Script Date: 12/31/2019 9:08:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Document](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[DocNumber] [varchar](50) NOT NULL,
	[DocName] [varchar](50) NOT NULL,
	[DocumentTypeId] [int] NOT NULL,
	[picture] [varchar](max) NULL,
 CONSTRAINT [PK_Document] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DocumentType]    Script Date: 12/31/2019 9:08:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DocumentType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DocumentType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DocumentXPerson]    Script Date: 12/31/2019 9:08:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DocumentXPerson](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PersonId] [bigint] NOT NULL,
	[DocumentId] [bigint] NOT NULL,
	[location] [geography] NULL,
	[WasFound] [bit] NULL,
	[DateFound] [date] NULL,
	[Wasloosed] [bit] NULL,
	[DateLost] [date] NULL,
 CONSTRAINT [PK_DocumentXPerson] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 12/31/2019 9:08:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[LastName] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
	[Phone] [varchar](50) NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Document]  WITH CHECK ADD  CONSTRAINT [FK_Document_DocumentType] FOREIGN KEY([DocumentTypeId])
REFERENCES [dbo].[DocumentType] ([Id])
GO
ALTER TABLE [dbo].[Document] CHECK CONSTRAINT [FK_Document_DocumentType]
GO
ALTER TABLE [dbo].[DocumentXPerson]  WITH CHECK ADD  CONSTRAINT [FK_DocumentXPerson_Document] FOREIGN KEY([DocumentId])
REFERENCES [dbo].[Document] ([Id])
GO
ALTER TABLE [dbo].[DocumentXPerson] CHECK CONSTRAINT [FK_DocumentXPerson_Document]
GO
ALTER TABLE [dbo].[DocumentXPerson]  WITH CHECK ADD  CONSTRAINT [FK_DocumentXPerson_Person] FOREIGN KEY([PersonId])
REFERENCES [dbo].[Person] ([Id])
GO
ALTER TABLE [dbo].[DocumentXPerson] CHECK CONSTRAINT [FK_DocumentXPerson_Person]
GO
USE [master]
GO
ALTER DATABASE [FindMyStuffDB] SET  READ_WRITE 
GO
